[package]
name = "public_ledger"
version = "0.1.0"
edition = "2024"

[dependencies]
ring = "0.17.13"
rand = "0.9.0"
tonic = "0.13.0"
prost = "0.13.5"
tokio = { version = "1.44.1", features = ["full"] }
eframe = "0.27"
egui = "0.27"

[build-dependencies]
tonic-build = "0.13.0"